### ISSUE TITLE
request loop when submitting problems on production environment

### ISSUE THREAD

**Issue by lportemo** [prologin/academy-site#12]

**Comment by AurelReb** [comment]
I think it's the purpose of https://github.com/prologin/academy-site/blob/5b836e2beb226b4b1c6a5614b82e31782fd626ca/front/src/config/store.js#L155-L173
Or maybe I didn't understand the issue

**Comment by lportemo** [comment]
try to make a submission on https://academie.prologin.org. It hangs forever
