### ISSUE TITLE
should submissions automatically run on save ?

### ISSUE THREAD

**Issue by lportemo** [prologin/academy-site#7]

**Comment by Elfikurr** [comment]
As of now, I cannot see a use case for this.
If I save my submission without anything in it, I probably don't want it to be run.

Furthermore, users might not understand errors returned by this kind of submissions (they didn't click on anything, and they get errors, it might be confusing).

Did you have something in mind ?

**Comment by lportemo** [comment]
Ok thanks for all the responses, I'm closing the issue :)
